# :noTabs=true:
# (c) Copyright Rosetta Commons Member Institutions.
# (c) This file is part of the Rosetta software suite and is made available under license.
# (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
# (c) For more information, see http://www.rosettacommons.org. Questions about this can be
# (c) addressed to University of Washington CoMotion, email: license@uw.edu.

targets = [
	"1CLV",
	"1F6M",
	"1FCC",
	"1FFW",
	"1FLE",
	"1GL1",
	"1GXD",
	"1H9D",
	"1HCF",
	"1JIW",
	"1JK9",
	"1JTG",
	"1JWH",
	"1JZD",
	"1LFD",
	"1MQ8",
	"1OC0",
	"1OFU",
	"1OYV",
	"1PVH",
	"1R6Q",
	"1RV6",
	"1SYX",
	"1US7",
	"1WDW",
	"1XU1",
	"1ZHH",
	"1ZLI",
	"1ZM4",
	"2A5T",
	"2A9K",
	"2ABZ",
	"2AYO",
	"2B4J",
	"2FJU",
	"2G77",
	"2I9B",
	"2IDO",
	"2J0T",
	"2J7P",
	"2O3B",
	"2OOR",
	"2OUL",
	"2OZA",
	"2VDB",
	"2Z0E",
	"3BP8",
	"3CPH",
	"3D5S",
	"3SGQ",
	"4CPA",
	"BOYV",
	]
