NATAA

start

 1 A ALLAAxc
 3 A ALLAAxc
 5 A ALLAAxc
 7 A ALLAAxc
 9 A ALLAAxc
11 A ALLAAxc

# We can't quite do ANYTHING for betas b/c if you do, you crash --
# we need a resfile. Sad!
 2 A NATRO #PIKAA X[B3D]X[B3E]X[B3F]X[B3G]X[B3I]X[B3K]X[B3L]X[B3N]X[B3Q]X[B3S]X[B3T]X[B3V]X[B3Y]
12 A NATRO #PIKAA X[B3D]X[B3E]X[B3F]X[B3G]X[B3I]X[B3K]X[B3L]X[B3N]X[B3Q]X[B3S]X[B3T]X[B3V]X[B3Y]

 4 A PIKAA X[PRE_METHYLENE_PARA_POLYARAMID_ASP]X[PRE_METHYLENE_PARA_POLYARAMID_GLU]X[PRE_METHYLENE_PARA_POLYARAMID_PHE]X[PRE_METHYLENE_PARA_POLYARAMID_ILE]X[PRE_METHYLENE_PARA_POLYARAMID_LEU]X[PRE_METHYLENE_PARA_POLYARAMID_ETHYL]X[PRE_METHYLENE_PARA_POLYARAMID_PROPYL]X[PRE_METHYLENE_PARA_POLYARAMID_ORN]X[PRE_METHYLENE_PARA_POLYARAMID_DAB]X[PRE_METHYLENE_PARA_POLYARAMID_DAP]
 6 A PIKAA X[POST_METHYLENE_PARA_POLYARAMID_ASP]X[POST_METHYLENE_PARA_POLYARAMID_GLU]X[POST_METHYLENE_PARA_POLYARAMID_PHE]X[POST_METHYLENE_PARA_POLYARAMID_ILE]X[POST_METHYLENE_PARA_POLYARAMID_LEU]X[POST_METHYLENE_PARA_POLYARAMID_ETHYL]X[POST_METHYLENE_PARA_POLYARAMID_PROPYL]X[POST_METHYLENE_PARA_POLYARAMID_ORN]X[POST_METHYLENE_PARA_POLYARAMID_DAB]X[POST_METHYLENE_PARA_POLYARAMID_DAP]
 8 A PIKAA X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_ASP]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_GLU]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_PHE]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_ILE]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_LEU]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_ETHYL]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_PROPYL]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_ORN]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_DAB]X[PRE_METHYLENE_POST_METHYLENE_ORTHO_POLYARAMID_DAP]
10 A PIKAA X[META_POLYARAMID_ASP]X[META_POLYARAMID_GLU]X[META_POLYARAMID_PHE]X[META_POLYARAMID_ILE]X[META_POLYARAMID_LEU]X[META_POLYARAMID_ETHYL]X[META_POLYARAMID_PROPYL]X[META_POLYARAMID_ORN]X[META_POLYARAMID_DAB]X[META_POLYARAMID_DAP]

