<dock_design>
	<TASKOPERATIONS>
		<InitializeFromCommandline name=IFC/>
		<OperateOnCertainResidues name=AUTOprot>
			<AddBehaviorRLT behavior=AUTO/>
			<ResidueHasProperty property=PROTEIN/>
		</OperateOnCertainResidues>
		<OperateOnCertainResidues name=nopackPROT>
			<PreventRepackingRLT/>
			<ResidueHasProperty property=PROTEIN/>
		</OperateOnCertainResidues>
		<OperateOnCertainResidues name=nodesignPROT>
			<RestrictToRepackingRLT/>
			<ResidueHasProperty property=PROTEIN/>
		</OperateOnCertainResidues>
		<RestrictDesignToProteinDNAInterface name=RDTPDI/>
		<WatsonCrickRotamerCouplings name=WCRC/>
	</TASKOPERATIONS>
	<SCOREFXNS>
		<dna_elec_nobp weights=dna_elec_nobp/>
		<dnasoftrep_hackelec weights=phil_dna_nodnabp_hackelec/>
		<dnasoftrep_hackelec_dnabp weights=phil_dnabp_hackelec/>
		<ddg weights=ddg/>
		<interface weights=interface/>
	</SCOREFXNS>
	<MOVERS>
		<ScoreMover name=score scorefxn=dnasoftrep_hackelec_dnabp/>
		<MinMover name=min scorefxn=dnasoftrep_hackelec_dnabp chi=1/>
		<PackRotamersMover name=design scorefxn=dnasoftrep_hackelec_dnabp task_operations=IFC,AUTOprot,nopackPROT,RDTPDI,WCRC nloop=100/>
	</MOVERS>
	<PROTOCOLS>
		<Add mover_name=design/>
	</PROTOCOLS>
</dock_design>
