# -*- tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
# vi: set ts=2 noet:
#
# (c) Copyright Rosetta Commons Member Institutions.
# (c) This file is part of the Rosetta software suite and is made available under license.
# (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
# (c) For more information, see http://www.rosettacommons.org. Questions about this can be
# (c) addressed to University of Washington UW TechTransfer, email: license@u.washington.edu.

iscript_fname = "compare_sample_sources_iscript.R"

iscript_header <- function(){
  cat(paste(
"# -*- tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
# vi: set ts=2 noet:
#
# (c) Copyright Rosetta Commons Member Institutions.
# (c) This file is part of the Rosetta software suite and is made available under license.
# (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
# (c) For more information, see http://www.rosettacommons.org. Questions about this can be
# (c) addressed to University of Washington UW TechTransfer, email: license@u.washington.edu.

####################################################################
#                                                                  #
#     This script is auto-generated by compare_sample_sources.R    #
#                                                                  #
#                                                                  #
#  Use this to interactively develop or refine an analysis script  #
#                                                                  #
####################################################################


#
# To use, from with in R run:
#
#   source(\"",iscript_fname,"\")
#

", sep=""), file=iscript_fname, append=FALSE)
}

iscript_libraries <- function(libraries){
  for(lib in libraries){
    cat("library(", lib, ")\n", file=iscript_fname, sep="", append=TRUE)
  }
  cat("\n", file=iscript_fname, append=TRUE)
}

iscript_base_dir <- function(base_dir){
	cat("base_dir <- \"", base_dir , "\"\n", file=iscript_fname, sep="", append=T)
}

iscript_includes <- function(includes){
  for( inc in includes){
    cat("source(\"", inc, "\")\n", file=iscript_fname, sep="", append=TRUE)
  }
  cat("\n", file=iscript_fname, append=TRUE)
}


iscript_setup_analysis_manager <- function(analysis_manager_db){
	cat("analysis_manager_con <- initialize_analysis_manager_db(\n",
		"	\"", analysis_manager_db, "\")\n\n",
		file=iscript_fname, append=TRUE, sep="")
}

iscript_sample_sources <- function(sample_sources){
  cat("#directory were the .db3 feature database are located\n",
      file=iscript_fname, append=TRUE)
  cat("sample_sources <- get_sample_sources(c(
	\"", paste(sample_sources$fname, collapse="\",\n	\""), "\"))\n",
      file=iscript_fname, sep="", append=TRUE)
  cat("\n", file=iscript_fname, append=TRUE)
}

iscript_output_dir <- function(output_dir){
  cat("#directory where the output should be generated\n",
      file=iscript_fname, append=TRUE)
  cat("output_dir <- \"", output_dir, "\"\n",
      file=iscript_fname, sep="", append=TRUE)
  cat("\n", file=iscript_fname, append=TRUE)
}

iscript_output_formats <- function(output_formats){
  ids <- c()
  for(output_format in output_formats[,1]) ids <- c(ids, output_format)
  cat("#file format for plots
#See scripts/methods/output_formats.R for more formats\n",
      file=iscript_fname, append=TRUE)
  cat("output_formats <- rbind(\n	", paste(ids, collapse=",\n	"),
      ")\n",
      file=iscript_fname, sep="", append=TRUE)
  cat("\n", file=iscript_fname, append=TRUE)
}

iscript_db_cache_size <- function(db_cache_size){
  cat("#number of 1k pages to use as cache\n",
      file=iscript_fname, append=TRUE)
  cat("db_cache_size <- ", db_cache_size,
      file=iscript_fname, sep="", append=TRUE)
  cat("\n", file=iscript_fname, append=TRUE)
}

iscript_source_scripts <- function(scripts){
  cat("\n", file=iscript_fname, append=TRUE)
  cat("#Source these analysis scripts:\n",
      file=iscript_fname, append=TRUE)
	cat("feature_analyses <- c()\n",
			file=iscript_fname, append=TRUE)
  for(script in scripts){
    cat("source(\"", script, "\")\n",
        file=iscript_fname, sep="", append=TRUE)
  }
}

iscript_run_feature_analyses <- function(){
  cat("\n", file=iscript_fname, append=TRUE)
	cat("#Run these feature_analyses:\n",
			file=iscript_fname, append=TRUE)
	cat("for(features_analysis in feature_analyses){

	# In order to assist in running the script interactively, rather
	# than just running it, setup the input parameters in the current
	# evironment and then evaluate the body of the function in the
	# current frame as well..

	self <- features_analysis
	eval(body(features_analysis@run))

}\n\n",
			file=iscript_fname, append=TRUE)
}
