# This is a .comp file for requiring that a structure have one and only one alanine residue. 

# This penalty definition block specifies that, for alanine, there will be a 100-point penalty for having ANY fewer or ANY more than the desired number of alanine residues.
PENALTY_DEFINITION
TYPE ALA
DELTA_START -1
DELTA_END 1
PENALTIES 100 0 100
ABSOLUTE 1
BEFORE_FUNCTION CONSTANT
AFTER_FUNCTION CONSTANT
END_PENALTY_DEFINITION
