# This is a .comp file for requiring that a structure have one and only one tryptophan residue. 
# File created 21 July 2015 by Vikram K. Mulligan (vmullig@uw.edu), Baker laboratory.

# This penalty definition block specifies that, for tryptophan, there will be a 100-point penalty for
# having ANY fewer or ANY more than the desired number of tryptophan residues.
PENALTY_DEFINITION
TYPE PRO
DELTA_START -2
DELTA_END 2
PENALTIES 100 50 0 20 40
FRACTION 0.2
END_PENALTY_DEFINITION
