python makeFiles.py basic
python makeFiles.py core.1
python makeFiles.py core.2
python makeFiles.py core.3
python makeFiles.py core.4
python makeFiles.py core.5
python makeFiles.py numeric
python makeFiles.py ObjexxFCL
python makeFiles.py protocols
python makeFiles.py utility


# Remove references to VS2010 project files.
# Doesn't affect project files generated by
# older versions of Visual Studio.
python fixvc.py boinc_mini.sln > boinc_mini.sln.new
mv boinc_mini.sln.new boinc_mini.sln
