// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available
// (c) under license. The Rosetta software is developed by the contributing
// (c) members of the Rosetta Commons. For more information, see
// (c) http://www.rosettacommons.org. Questions about this can be addressed to
// (c) University of Washington UW TechTransfer,email:license@u.washington.edu.

/// @file protocols/constraint_generator/ConstraintsManager.hh
/// @brief Manages lists of constraints generated by ConstraintGenerators
/// @author Tom Linsky (tlinsky@uw.edu)

#ifndef INCLUDED_protocols_constraint_generator_ConstraintsManager_hh
#define INCLUDED_protocols_constraint_generator_ConstraintsManager_hh

// Unit headers
#include <protocols/constraint_generator/ConstraintsManager.fwd.hh>

// Core headers
#include <core/scoring/constraints/Constraint.fwd.hh>

// Utility headers
#include <utility/SingletonBase.hh>

// C++ headers
#include <map>

namespace protocols {
namespace constraint_generator {

///@brief Manages lists of constraints generated by ConstraintGenerators
class ConstraintsManager : public utility::SingletonBase< ConstraintsManager > {

private: //types
	typedef std::map< std::string, core::scoring::constraints::ConstraintCOPs > ConstraintsMap;

public: // constructors/destructors
	ConstraintsManager();
	virtual ~ConstraintsManager();

	static ConstraintsManager *
	create_singleton_instance();

public:
	bool
	constraints_exist( std::string const & name ) const;

	core::scoring::constraints::ConstraintCOPs const &
	retrieve_constraints( std::string const & name ) const;

	void
	store_constraints( std::string const & name, core::scoring::constraints::ConstraintCOPs const & constraints );

	void
	remove_constraints( std::string const & name );

private:
	void
	print_valid_names( std::ostream & os ) const;

private:
	ConstraintsMap cst_map_;

};


} //protocols
} //constraint_generator

#endif //INCLUDED_protocols_constraint_generator_ConstraintsManager_hh
