<ROSETTASCRIPTS>
	<TASKOPERATIONS>
		<InitializeFromCommandline name="IFC"/>
		<IncludeCurrent name="IC"/>
		<ReadResfile name="RRF"/>
		<RestrictDesignToProteinDNAInterface name="DnaInt" base_only="1" z_cutoff="2.0"/>
	</TASKOPERATIONS>
	<SCOREFXNS>
		<ScoreFunction name="DNA" weights="dna"/>
		<ScoreFunction name="DNAGB" weights="dna_gb"/>
	</SCOREFXNS>
	<FILTERS>
		<FalseFilter name="falsefilter"/>
	</FILTERS>
	<MOVERS>
		<PackRotamersMover name="PackRot" scorefxn="DNA" task_operations="IFC,IC,RRF,DnaInt"/>
	</MOVERS>
	<PROTOCOLS>
		<Add mover_name="PackRot"/>
	</PROTOCOLS>

</ROSETTASCRIPTS>
