#!/bin/bash 

if [[ $# -eq 1 ]]; then cat /dev/stdin | awk  "{ print \$$1 }"; fi
if [[ $# -eq 2 ]]; then cat /dev/stdin | awk  "{ print \$$1,\$$2 }"; fi
if [[ $# -eq 3 ]]; then cat /dev/stdin | awk  "{ print \$$1,\$$2,\$$3 }"; fi
if [[ $# -eq 4 ]]; then cat /dev/stdin | awk  "{ print \$$1,\$$2,\$$3,\$$4 }"; fi
if [[ $# -eq 5 ]]; then cat /dev/stdin | awk  "{ print \$$1,\$$2,\$$3,\$$4,\$$5 }"; fi
