// #error Don't include; for documentation only.

/// @namespace protocols::kinematic_closure::solution_pickers
///
/// @brief Algorithms for picking one of the 0 to 16 solutions generated by 
/// kinematic closure.
///
/// @details The classes in this namespace are intended to be constructed and 
/// configured by the programmer, but used internally by samplers::KicSampler.  
/// So in most cases, you only have to worry about the constructor.  If you 
/// want to create a new solution picking algorithm, just inherit from 
/// SolutionPicker and reimplement SolutionPicker::pick_and_apply().
