TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","N",1)["SHIFT"].c_str() ),  114.266, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","N",1)["RC_SHIFT"].c_str() ),  114.554, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","N",1)["SS_SHIFT"].c_str() ),   -0.275, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","HA",1)["SHIFT"].c_str() ),    4.968, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","HA",1)["RC_SHIFT"].c_str() ),    4.350, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","HA",1)["SS_SHIFT"].c_str() ),    0.471, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","C",1)["SHIFT"].c_str() ),  174.145, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","C",1)["RC_SHIFT"].c_str() ),  174.700, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","C",1)["SS_SHIFT"].c_str() ),   -0.499, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","CA",1)["SHIFT"].c_str() ),   60.748, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ),   62.100, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ),   -1.325, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","CB",1)["SHIFT"].c_str() ),   70.306, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ),   68.868, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ),    1.454, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","HN",1)["SHIFT"].c_str() ),    8.534, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ),    8.240, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","6","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ),    0.307, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","N",1)["SHIFT"].c_str() ),  120.340, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","N",1)["RC_SHIFT"].c_str() ),  120.200, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","N",1)["SS_SHIFT"].c_str() ),   -0.028, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","HA",1)["SHIFT"].c_str() ),    4.774, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","HA",1)["RC_SHIFT"].c_str() ),    4.350, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","HA",1)["SS_SHIFT"].c_str() ),    0.293, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","C",1)["SHIFT"].c_str() ),  175.595, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","C",1)["RC_SHIFT"].c_str() ),  176.600, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","C",1)["SS_SHIFT"].c_str() ),   -1.144, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","CA",1)["SHIFT"].c_str() ),   54.178, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ),   56.400, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ),   -2.351, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","CB",1)["SHIFT"].c_str() ),   32.108, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ),   29.700, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ),    2.325, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","HN",1)["SHIFT"].c_str() ),    8.860, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ),    8.360, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","44","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ),    0.357, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","N",1)["SHIFT"].c_str() ),  116.973, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","N",1)["RC_SHIFT"].c_str() ),  115.700, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","N",1)["SS_SHIFT"].c_str() ),    1.262, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","HA",1)["SHIFT"].c_str() ),    4.293, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","HA",1)["RC_SHIFT"].c_str() ),    4.470, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","HA",1)["SS_SHIFT"].c_str() ),   -0.194, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","C",1)["SHIFT"].c_str() ),  175.480, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","C",1)["RC_SHIFT"].c_str() ),  174.600, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","C",1)["SS_SHIFT"].c_str() ),    0.864, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","CA",1)["SHIFT"].c_str() ),   60.187, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ),   58.200, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ),    1.974, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","CB",1)["SHIFT"].c_str() ),   63.034, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ),   63.200, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ),   -0.174, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","HN",1)["SHIFT"].c_str() ),    8.650, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ),    8.310, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","55","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ),    0.334, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","N",1)["SHIFT"].c_str() ),  118.777, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","N",1)["RC_SHIFT"].c_str() ),  120.400, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","N",1)["SS_SHIFT"].c_str() ),   -1.630, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","HA",1)["SHIFT"].c_str() ),    4.628, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","HA",1)["RC_SHIFT"].c_str() ),    4.640, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","HA",1)["SS_SHIFT"].c_str() ),   -0.021, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","C",1)["SHIFT"].c_str() ),  177.343, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","C",1)["RC_SHIFT"].c_str() ),  176.300, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","C",1)["SS_SHIFT"].c_str() ),    1.043, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","CA",1)["SHIFT"].c_str() ),   54.038, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ),   54.000, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ),    0.035, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","CB",1)["SHIFT"].c_str() ),   40.817, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ),   40.800, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ),    0.026, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","HN",1)["SHIFT"].c_str() ),    7.974, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ),    8.370, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","56","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ),   -0.375, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","N",1)["SHIFT"].c_str() ),  123.903, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","N",1)["RC_SHIFT"].c_str() ),  121.223, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","N",1)["SS_SHIFT"].c_str() ),    2.596, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","HA",1)["SHIFT"].c_str() ),    5.542, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","HA",1)["RC_SHIFT"].c_str() ),    4.340, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","HA",1)["SS_SHIFT"].c_str() ),    0.852, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","C",1)["SHIFT"].c_str() ),  176.198, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","C",1)["RC_SHIFT"].c_str() ),  176.870, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","C",1)["SS_SHIFT"].c_str() ),   -0.744, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","CA",1)["SHIFT"].c_str() ),   53.298, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ),   54.840, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ),   -1.648, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","CB",1)["SHIFT"].c_str() ),   45.559, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ),   42.059, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ),    3.342, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","HN",1)["SHIFT"].c_str() ),    8.762, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ),    8.230, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","76","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ),    0.409, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","N",1)["SHIFT"].c_str() ),  119.413, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","N",1)["RC_SHIFT"].c_str() ),  120.400, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","N",1)["SS_SHIFT"].c_str() ),   -1.045, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","HA",1)["SHIFT"].c_str() ),    4.591, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","HA",1)["RC_SHIFT"].c_str() ),    4.320, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","HA",1)["SS_SHIFT"].c_str() ),    0.351, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","C",1)["SHIFT"].c_str() ),  175.667, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","C",1)["RC_SHIFT"].c_str() ),  176.600, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","C",1)["SS_SHIFT"].c_str() ),   -0.958, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","CA",1)["SHIFT"].c_str() ),   54.511, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ),   56.287, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ),   -1.769, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","CB",1)["SHIFT"].c_str() ),   35.725, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ),   32.500, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ),    3.229, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","HN",1)["SHIFT"].c_str() ),    8.548, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ),    8.250, TOLERATED_ERROR);
TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","77","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ),    0.223, TOLERATED_ERROR);

		//now check a couple of the values
		//HN  residue 5 8.4877 0.254765 0 8.15 0.184839 0.421
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","5","ATOMNAME","HN",1)["SHIFT"].c_str() ), 8.4877, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","5","ATOMNAME","HN",1)["HM_SHIFT"].c_str() ), 0.2547, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","5","ATOMNAME","HN",1)["EF_SHIFT"].c_str() ), 0, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","5","ATOMNAME","HN",1)["RC_SHIFT"].c_str() ), 8.15, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","5","ATOMNAME","HN",1)["SS_SHIFT"].c_str() ), 0.184, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","5","ATOMNAME","HN",1)["SIGMA"].c_str() ), 0.421, TOLERATED_ERROR );
		//CB  residue 11 42.4556 0.081169 0 40.8 1.60687 1.028
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","11","ATOMNAME","CB",1)["SHIFT"].c_str() ), 42.4556, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","11","ATOMNAME","CB",1)["HM_SHIFT"].c_str() ), 0.0811, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","11","ATOMNAME","CB",1)["EF_SHIFT"].c_str() ), 0, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","11","ATOMNAME","CB",1)["RC_SHIFT"].c_str() ), 40.8, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","11","ATOMNAME","CB",1)["SS_SHIFT"].c_str() ), 1.607, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","11","ATOMNAME","CB",1)["SIGMA"].c_str() ), 1.028, TOLERATED_ERROR );
		//CA residue 14 55.749 -0.0209684 0 56.287 -0.525428 1.111
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","14","ATOMNAME","CA",1)["SHIFT"].c_str() ), 55.749, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","14","ATOMNAME","CA",1)["HM_SHIFT"].c_str() ), -0.02096, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","14","ATOMNAME","CA",1)["EF_SHIFT"].c_str() ), 0, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","14","ATOMNAME","CA",1)["RC_SHIFT"].c_str() ), 56.287, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","14","ATOMNAME","CA",1)["SS_SHIFT"].c_str() ), -0.525428, TOLERATED_ERROR );
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","14","ATOMNAME","CA",1)["SIGMA"].c_str() ), 1.111, TOLERATED_ERROR );
		//C residue 8 173.788
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","8","ATOMNAME","C",1)["SHIFT"].c_str() ), 173.788, TOLERATED_ERROR );
		//N  residue 57 108.803
		TS_ASSERT_DELTA( atof( Pred_Sum.getEntry("RESID","57","ATOMNAME","N",1)["SHIFT"].c_str() ), 108.803, TOLERATED_ERROR );
