// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington CoMotion, email: license@uw.edu.

/// @file protocols/cyclic_peptide_predict/HierarchicalHybridJD_JobResultsSummary.hh
/// @brief A small helper class used by the SimpleCycpepPredict_MPI class -- headers.
/// @author Vikram K. Mulligan, Baker laboratory (vmullig@uw.edu)

#ifndef INCLUDED_protocols_cyclic_peptide_predict_HierarchicalHybridJD_JobResultsSummary_hh
#define INCLUDED_protocols_cyclic_peptide_predict_HierarchicalHybridJD_JobResultsSummary_hh

// Unit Headers
#include <protocols/cyclic_peptide_predict/HierarchicalHybridJD_JobResultsSummary.fwd.hh>
#include <protocols/cyclic_peptide_predict/HierarchicalHybridJD_ResultsSummaryBase.hh>

// Package Headers
#include <core/pose/Pose.fwd.hh>
#include <core/types.hh>

// Project Headers

// Utility Headers
#include <utility/VirtualBase.hh>
#include <utility/vector1.hh>

// C++ headers
#include <cstdio>

namespace protocols {
namespace cyclic_peptide_predict {

/// @brief A class for summarizing the result of an MPI-mode job run with the SimpleCycpepPredictApplication.
/// @author Vikram K. Mulligan, Baker laboratory (vmullig@uw.edu)
class HierarchicalHybridJD_JobResultsSummary : public HierarchicalHybridJD_ResultsSummaryBase
{
public:
	/// @brief Constructor
	///
	HierarchicalHybridJD_JobResultsSummary() = default;

	/// @brief Copy constructor
	HierarchicalHybridJD_JobResultsSummary( HierarchicalHybridJD_JobResultsSummary const & ) = default;

	/// @brief Constructor with options
	///
	HierarchicalHybridJD_JobResultsSummary(
		int const originating_node_MPI_rank,
		core::Size const jobindex_on_originating_node,
		core::Real const &pose_energy,
		core::Real const &rmsd,
		core::Size const hbonds,
		core::Size const cis_peptide_bonds
	);

	/// @brief Clone operator: make a copy of this object and return an OP to the copy.
	HierarchicalHybridJD_ResultsSummaryBaseOP clone() const override;

public:
	/// ------------- Getters -------------------------------

	/// @brief Get the energy of the pose generated by this job.
	///
	inline core::Real const & pose_energy() const { return pose_energy_; }

	/// @brief Get the RMSD of the pose generated by this job to native.
	///
	inline core::Real const & rmsd() const { return rmsd_; }

	/// @brief Get the number of hbonds of the pose generated by this job.
	///
	inline core::Size hbonds() const { return hbonds_; }

	/// @brief Get the number of cis-peptide bonds of the pose generated by this job.
	///
	inline core::Size cis_peptide_bonds() const { return cis_peptide_bonds_; }

	/// @brief Print a summary of this object to a stream.
	///
	void show( std::ostream & out ) const;

public:
	/// ------------- Setters -------------------------------

	/// @brief Set the energy of the pose generated by this job.
	///
	void set_pose_energy( core::Real const &val );

	/// @brief Set the RMSD of the pose generated by this job to native.
	///
	void set_rmsd( core::Real const &val );

	/// @brief Set the number of hbonds of the pose generated by this job.
	///
	void set_hbonds( core::Size const val);

	/// @brief Set the number of cis-peptide bonds of the pose generated by this job.
	///
	void set_cis_peptide_bonds( core::Size const val);

private:
	/// ------------- Data -------------------------------
	/// ----- When you add new data to this class, -------
	/// ----- you must update the options constructor ----

	/// @brief The energy of the resulting pose.
	///
	core::Real pose_energy_ = 0.0;

	/// @brief The rmsd of this pose to native.
	///
	core::Real rmsd_ = 0.0;

	/// @brief Number of hydrogen bonds.
	///
	core::Size hbonds_ = 0;

	/// @brief Number of cis-peptide bonds.
	///
	core::Size cis_peptide_bonds_ = 0;

};

} //cyclic_peptide
} //protocols

#endif //INCLUDED_protocols_cyclic_peptide_predict_HierarchicalHybridJD_JobResultsSummary_hh

