// vi: set ts=2 noet;
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington UW TechTransfer, email: license@u.washington.edu.

/// @file AssemblyConstraintsMover.hh
///
/// @brief A simple mover that reads a NativeRotamersFile generated by a an AssemblyMover run and generates the necessary
/// ResidueType constraints to add to the pose
/// @author Tim Jacobs


#ifndef INCLUDED_protocols_sewing_sampling_AssemblyConstraintsMover_HH
#define INCLUDED_protocols_sewing_sampling_AssemblyConstraintsMover_HH

// Unit Headers
#include <protocols/sewing/sampling/AssemblyConstraintsMover.fwd.hh>
#include <protocols/moves/Mover.hh>
#include <core/pack/task/operation/TaskOperation.hh>
#include <core/pack/task/operation/TaskOperationCreator.hh>

// Package Headers
#include <protocols/sewing/util/io.hh>

namespace protocols {
namespace sewing  {

//////////////ReadNativeRotamersFile/////////////////

class ReadNativeRotamersFileCreator : public core::pack::task::operation::TaskOperationCreator {
public:
	virtual
	core::pack::task::operation::TaskOperationOP
	create_task_operation() const;

	virtual
	std::string keyname()
	const { return "ReadNativeRotamersFile"; }
};


class ReadNativeRotamersFile : public core::pack::task::operation::TaskOperation
{
public:
	typedef core::pack::task::operation::TaskOperation parent;

public:

	ReadNativeRotamersFile();
	virtual ~ReadNativeRotamersFile();

	virtual
	core::pack::task::operation::TaskOperationOP
	clone() const;

	virtual
	void
	apply(
		core::pose::Pose const &,
		core::pack::task::PackerTask &
	) const;

	void native_rotamers_map(
		NativeRotamersMap const & nat_ro_map
	);

	NativeRotamersMap const &
	native_rotamers_map() const;

	virtual void parse_tag(
		TagCOP, DataMap &
	);

private:
	NativeRotamersMap nat_ro_map_;
};

//////////////ReadRepeatNativeRotamersFile/////////////////

class ReadRepeatNativeRotamersFileCreator : public core::pack::task::operation::TaskOperationCreator {
public:
	virtual
	core::pack::task::operation::TaskOperationOP
	create_task_operation() const;

	virtual
	std::string keyname()
	const { return "ReadRepeatNativeRotamersFile"; }
};

class ReadRepeatNativeRotamersFile : public ReadNativeRotamersFile
{
public:
	ReadNativeRotamersFile parent;

public:

	ReadRepeatNativeRotamersFile();
	virtual ~ReadRepeatNativeRotamersFile();

	virtual
	core::pack::task::operation::TaskOperationOP
	clone() const;

	virtual
	void
	apply(
		core::pose::Pose const &,
		core::pack::task::PackerTask &
	) const;
};

//////////////AssemblyConstraintsMover/////////////////

class AssemblyConstraintsMover : public protocols::moves::Mover {

public:

	AssemblyConstraintsMover();

	AssemblyConstraintsMover(
		NativeRotamersMap const & nat_ro_map,
		core::Real neighbor_cutoff,
		core::Real base_native_bonus
	);

	protocols::moves::MoverOP
	clone() const;

	protocols::moves::MoverOP
	fresh_instance() const;

	std::string
	get_name() const;

	void
	nat_ro_map(
		NativeRotamersMap const & nat_ro_map
	);

	void
	neighbor_cutoff(
		core::Real neighbor_cutoff
	);

	void
	base_native_bonus(
		core::Real base_native_bonus
	);

	virtual
	void
	apply(
		core::pose::Pose & pose
	);

	void
	apply_repeat(
		core::pose::Pose & pose
	);

	virtual
	void
	parse_my_tag(
		TagCOP tag,
		basic::datacache::DataMap & /*data*/,
		protocols::filters::Filters_map const & /*filters*/,
		protocols::moves::Movers_map const & /*movers*/,
		core::pose::Pose const & /*pose*/
	);

private:

	NativeRotamersMap nat_ro_map_;

	//Only favor 'natives' that have >= this many neighbors
	core::Real neighbor_cutoff_;

	//Favor all 'natives' by this amount (in REU)
	core::Real base_native_bonus_;

};

} //sewing
} //protocols

#endif
