#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

# Update current HEAD to use branch pointer, if possible 

# clone-by-sha leaves working directory in detached head state, even though
# we're building a "branch". Resolves issues with "version.py" marking the
# current branch as HEAD during development builds by creating a local branch
# pointer.

set -x 

if [[ ! -z "${BUILDKITE_BRANCH:-}" ]]; then
  # -B to force reset a local ref if it exists
  git checkout -B "${BUILDKITE_BRANCH}"
fi
