#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

# Update current HEAD to use branch pointer, if possible 
# resolves issues when clone-by-sha leaves a working directory 
# in detached head state.

set -x 

git fetch

if ((git describe --all --exact-match | grep -E 'heads|remotes') 2> /dev/null 1> /dev/null) ; then
  HEAD_BRANCH=`git describe --all --exact-match | grep -E 'heads|remotes'`
  if [[ $HEAD_BRANCH = "remotes"* ]]; then
    git checkout -t ${HEAD_BRANCH#remotes/} -B ${HEAD_BRANCH#remotes/*/}
  elif [[ $HEAD_BRANCH = "heads"* ]]; then
    git checkout ${HEAD_BRANCH#heads/}
  else
    exit 0
  fi
fi
