#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

set -x

# Delete the local branch pointer created by post-checkout
CURRENT_HEAD=$(git symbolic-ref --short HEAD)

if [[ ! -z "${CURRENT_HEAD:-}" ]]; then
  # Move back to the a headless checkout
  git checkout `git rev-parse HEAD`

  # and delete the local branch pointer we made
  git branch -D "${CURRENT_HEAD#heads/}"
fi
