#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

set -x

# Delete the local branch pointer created by post-checkout

if [[ ! -z "${BUILDKITE_BRANCH:-}" ]]; then
  # Move back to the a headless checkout
  git checkout `git rev-parse HEAD`

  # and delete the local branch pointer we made
  git branch -D "${BUILDKITE_BRANCH}"
fi
