// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington CoMotion, email: license@uw.edu.

/// @file src/apps/pilot/ashworth/jd2_parser.cc
/// @brief Runs DockDesignParser via jd2

#include <protocols/jd2/JobDistributor.hh>
#include <protocols/moves/Mover.hh>
#include <protocols/dna/PDBOutput.hh>
#include <protocols/viewer/viewers.hh>
#include <core/pose/Pose.fwd.hh>
#include <devel/init.hh>
#include <basic/Tracer.hh>

//Auto Headers
#include <core/scoring/constraints/Constraint.hh>
#include <core/scoring/constraints/SequenceProfileConstraint.fwd.hh>


using namespace core;
using namespace scoring;
using namespace constraints;

using namespace protocols;
using namespace constraints_additional;
using namespace dna;
using namespace moves;
using namespace jd2;
using namespace viewer;

static basic::Tracer TR( "apps.pilot.ashworth.jd2_parser" );

class DummyMover : public Mover {
public:
	DummyMover() : Mover( "DummyMover" ) {}
	virtual ~DummyMover(){}
	virtual void apply( Pose & ) {
		TR << "DummyMover::apply() should never have been called!"
			<< " (JobDistributor/Parser should have replaced DummyMover.)" << std::endl;
		runtime_assert(false); // will enable a backtrace in gdb
	}
	virtual std::string get_name() const { return "DummyMover"; }
};

void *
my_main( void * )
{
	// register SequenceProfileConstraint with the ConstraintFactory so that it can be constructed from a constraint file
	// ConstraintIO::get_cst_factory().add_type(
	//  new core::scoring::constraints::SequenceProfileConstraint( Size(), utility::vector1< id::AtomID >(), NULL ) );

	// need a non-NULL MoverOP because jd2 may try to call Mover methods,
	// but jd2 should end up reassigning this pointer to real Mover generated by Parser
	MoverOP dummy_mover = new DummyMover;

	// loads dna-specific PDBOutput class into the JobDistributor
	JobDistributor::get_instance()->go( dummy_mover, new PDBOutput );


	TR << "*********************successful completion**************************" << std::endl;
}

int
main( int argc, char * argv [] )
{
	try {
		devel::init( argc, argv );
		viewer_main( my_main );
	} catch ( utility::excn::EXCN_Base const & e ) {
		std::cout << "caught exception " << e.msg() << std::endl;
		return -1;
	}
	return 0;
}
