// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington UW TechTransfer, email: license@u.washington.edu.

/// @file   protocols/jd3/deallocation/InputPoseDeallocationMessage.hh
/// @brief  The definition for class protocols::jd3::InputPoseDeallocationMessage
/// @author Andrew Leaver-Fay (aleaverfay@gmail.com)

#ifndef INCLUDED_protocols_jd3_deallocation_InputPoseDeallocationMessage_HH
#define INCLUDED_protocols_jd3_deallocation_InputPoseDeallocationMessage_HH

// Unit headers
#include <protocols/jd3/deallocation/InputPoseDeallocationMessage.fwd.hh>

// Package headers
#include <protocols/jd3/deallocation/DeallocationMessage.hh>

//utility headers
#include <utility/pointer/ReferenceCount.hh>
#include <core/types.hh>

#ifdef    SERIALIZATION
// Cereal headers
#include <cereal/types/polymorphic.fwd.hpp>
#endif // SERIALIZATION

namespace protocols {
namespace jd3 {
namespace deallocation {

/// @brief %InputPoseDeallocationMessage class holds the output that's generated by a Job over the course
/// of its execution.  The %InputPoseDeallocationMessage is handed by the JobQueen to the JobOutputWriter
/// objects, each of which have the opportunity to pull data out of the InputPoseDeallocationMessage
/// class.
class InputPoseDeallocationMessage : public DeallocationMessage
{
public:

	InputPoseDeallocationMessage();
	InputPoseDeallocationMessage( core::Size pose_id );
	virtual ~InputPoseDeallocationMessage();

	core::Size pose_id() const;
	void pose_id( core::Size setting );

private:
	core::Size pose_id_;

#ifdef    SERIALIZATION
public:
	template< class Archive > void save( Archive & arc ) const;
	template< class Archive > void load( Archive & arc );
#endif // SERIALIZATION

}; // InputPoseDeallocationMessage

} // namespace deallocation
} // namespace jd3
} // namespace protocols

#ifdef    SERIALIZATION

CEREAL_FORCE_DYNAMIC_INIT( protocols_jd3_deallocation_InputPoseDeallocationMessage )
#endif // SERIALIZATION


#endif //INCLUDED_protocols_jd3_deallocation_InputPoseDeallocationMessage_HH
