// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington CoMotion, email: license@uw.edu.

// This file has been generated by Py++.

#include "boost/python.hpp"

#include "core/import_pose/import_pose.hh"
#include "core/pose/Pose.hh"

namespace bp = boost::python;

using namespace core::import_pose;
/*
void
my_dump_pdb( core::pose::Pose const & pose,	std::string const & filename ) {
  dump_pdb(pose,filename);
}
*/

void __import_pose_by_hand_beginning__()
{
/*
  bp::def("core___io___pdb___pose_from_file", ( void (*)(core::pose::Pose &, std::string const &, bool) )( &pose_from_file) );
  bp::def("core___io___pdb___pose_from_file", ( void (*)(core::pose::Pose &, core::chemical::ResidueTypeSet const &, std::string const &, bool)  )( &pose_from_file) );

  bp::def("core___io___pdb___dump_pdb", &my_dump_pdb );
  */
}
