// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington CoMotion, email: license@uw.edu.

/// @file protocols/fold_from_loops/LabelPoseFromResidueSelectorMover.hh
/// @brief Adds labels to residues selected through a ResidueSelector
/// @author Jaume Bonet (jaume.bonet@gmail.com)

#ifndef INCLUDED_fold_from_loops_LabelPoseFromResidueSelectorMover_hh
#define INCLUDED_fold_from_loops_LabelPoseFromResidueSelectorMover_hh

// Unit headers
#include <protocols/fold_from_loops/LabelPoseFromResidueSelectorMover.fwd.hh>
#include <protocols/moves/Mover.hh>

// Protocol headers

// Core headers
#include <core/pose/Pose.fwd.hh>
#include <core/select/residue_selector/ResidueSelector.fwd.hh>

// Basic/Utility headers
#include <basic/datacache/DataMap.fwd.hh>

namespace protocols {
namespace fold_from_loops {

///@brief Adds constraints generated by ConstraintGenerators to a pose
class LabelPoseFromResidueSelectorMover : public protocols::moves::Mover {

public:
	LabelPoseFromResidueSelectorMover();
	LabelPoseFromResidueSelectorMover( core::select::residue_selector::ResidueSelectorCOP const & selector );
	LabelPoseFromResidueSelectorMover( core::select::residue_selector::ResidueSelectorCOP const & selector, std::string const & string );

	// destructor (important for properly forward-declaring smart-pointer members)
	~LabelPoseFromResidueSelectorMover() override;

	void
	apply( core::pose::Pose & pose ) override;

	/// @brief parse XML tag (to use this Mover in Rosetta Scripts)
	void
	parse_my_tag(
		utility::tag::TagCOP tag,
		basic::datacache::DataMap & data,
		protocols::filters::Filters_map const & filters,
		protocols::moves::Movers_map const & movers,
		core::pose::Pose const & reference_pose ) override;

	/// @brief required in the context of the parser/scripting scheme
	protocols::moves::MoverOP
	fresh_instance() const override;

	/// @brief required in the context of the parser/scripting scheme
	protocols::moves::MoverOP
	clone() const override;

	void
	residue_selector( core::select::residue_selector::ResidueSelectorCOP const & selector );

	void
	residue_selector( core::select::residue_selector::ResidueSelector const & selector );

	void
	label( std::string  const & label );

	void
	reverse( bool pick );

	std::string
	get_name() const override;

	static
	std::string
	mover_name();

	static
	void
	provide_xml_schema( utility::tag::XMLSchemaDefinition & xsd );

private:
	static
	core::select::residue_selector::ResidueSelectorCOP
	default_selector();

	static
	std::string
	default_label();

	static
	bool
	default_reverse();

private:
	core::select::residue_selector::ResidueSelectorCOP selector_;
	std::string label_;
	bool reverse_;
};

} //protocols
} //fold_from_loops

#endif //INCLUDED_fold_from_loops_LabelPoseFromResidueSelectorMover_hh
